### ISSUE TITLE
Develop consistent layout and color sheme

### ISSUE THREAD

**Issue by joshpal97** [CompileIO/compile.io#106]
# Description of Issue
As a User, I want to be able to recognize that compile.io is part of the Rose-Hulman family of applications

# Acceptance Criteria
- [ ] Have the website's layout and color scheme be consistent with other Rose Hulman Applications

# Notes
![image](https://user-images.githubusercontent.com/17732317/51444588-50bacd80-1cc7-11e9-9868-7ccedf576399.png)

**Comment by rileyma** [comment]
Duplicate #110
