### ISSUE TITLE
Refactoring Frontend

### ISSUE THREAD

**Issue by footezo** [CompileIO/compile.io#110]
As a developer, I need to follow the low fidelity prototypes that have been designed around use cases in order to ensure that the requirements will be fulfilled. 

# Acceptance Criteria
- [x] Breakdown low fidelity prototypes to one page index cards
- [x] Refactor existing frontend pages to fit with the low fidelity prototypes
- [x] Refactor design scheme to fit with Rose's style and colors
- [x] Adjust Use Cases in Requirements document in order to fit new prototypes

**Comment by rileyma** [comment]
Very broad issue. It is constantly changing as we create and add new low fis to the project. In the future, more specifics will be needed for issues like this one (names of use cases, name of prototypes, etc.)
