### ISSUE TITLE
Set Assignment Open/Close Times

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#114]
# Description of Issue
As a professor, I would like to set open/close times for my assignments, so that students cannot submit assignments earlier/later than what I intend.

# Acceptance Criteria
- [x] Create Low Fidelity Prototype
- [x] 12 Hour Clock EST
- [x] UI Implementation
- [x] Integration Testing

**Comment by joshpal97** [comment]
GH-154 closes #114
