### ISSUE TITLE
Professor Gradebook

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#115]
# Description of Issue
As a professor, I would like to view the grades for my students, as if I were viewing a gradebook.

# Acceptance Criteria
- [x] Export relevant metadata (User, Section, Assignment, Tests, Pass/Fail for each test)
- [x] Display metadata on the UI. Student's cannot view this.
- [x] Add functionality to export metadata to an excel file.
- [x] Integration Test

**Comment by donsisco** [comment]
Is this a per student export/ per Assignment export? or Both?

**Comment by rileyma** [comment]
From our understanding, this is per class. So this would be all the relevant metadata (listed above) for a particular class. 

A muddy point that still needs to be discussed with stakeholders is: should professors be able to see the metadata for sections they don't teach within a class that they do teach? For clarification, if I teach CSSE333 Sections 1 and 2, but not 3 and 4, should I be able to check 3 and 4s metadata? Our gut assumption is no, but we'd like an official answer from the stakeholders themselves. Based off the answer to this question, we will either filter/not filter the metadata "Section" category.

The metadata and it's format/order is based on feedback from Sriram as what a desirable Excel file export would look like.

Hope this clarifies.

**Comment by rileyma** [comment]
closed by pr #183
