### ISSUE TITLE
Create Tests for Services

### ISSUE THREAD

**Issue by joshpal97** [CompileIO/compile.io#134]
# Description of Issue
As a Developer, I need to be able to test whether my services that I have written on the frontend function as intended. The way to do that is to create tests for these services

# Acceptance Criteria
- [ ] Make sure all Services have an accompanying test, that tests whether the service is doing what is intended

**Comment by donsisco** [comment]
Also, please move test from `Frontend/compile-io-frontend-app/src/app/TestServices` to the same folder as services.

**Comment by joshpal97** [comment]
I am changing it to an 8 because I need to test the backend controllers, as well as the frontend services, we should probably split this up into 2 issues
