### ISSUE TITLE
Docker Has Problem with `mkdir` in VM's Linux Environment

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#146]
# Description of Issue
Currently, Compile.io runs end-to-end on a windows environment. Docker is having problems with the linux in the production VM's linux environment. Part of the problem is `mkdir` privileges with Docker; Docker doesn't have root privileges.

# Acceptance Criteria
- [ ] Fix `mkdir` privilege issue with Docker
- [ ] Run end-to-end manual test of the system and see that the Docker container does not error on build and returns the output from the JUnit tests it is running

**Comment by rileyma** [comment]
Possibly get a windows VM? Changes at this point would make it so we'd need separate releases for both Windows and Linux, either that or create a different `JavaBuilder.java` class for each OS.

The way `JavaBuilder.java` would need to change would require separate methods (or classes) for each OS, which isn't ideal.

Basically, system works on Windows, not linux, can't push system to VM because VM OS is Linux.

Talk to Darryl about Windows VM?

**Comment by rileyma** [comment]
Blocked by #164

**Comment by ghost** [comment]
I fixed this in branch 152 unknowingly
