### ISSUE TITLE
File Size Restriction - Frontend bug

### ISSUE THREAD

**Issue by joshpal97** [CompileIO/compile.io#155]
# Description of Issue
The alert for file size restriction pops up, but the file is still added on the frontend.

The backend doesn't allow the file to run, but the file shouldn't be added in the first place

# Acceptance Criteria
- [x] Alert pops up for file size being too big
- [x] File is not added to frontend

**Comment by ghost** [comment]
Fixed this issue a long time ago, don't remember which commit, but on current develop it is gone
