### ISSUE TITLE
Interview More Faculty: Subject - Professor UI

### ISSUE THREAD

**Issue by joshpal97** [CompileIO/compile.io#160]
# Description of Issue
As a Developer, I want to know exactly what my end clients want for the application, as a result, I need to talk to them to understand what exactly they need. In this case, I need to ask professors what they want from our UI.

# Acceptance Criteria
- [x] Reach out to professors we've talked to in the past
- [x] Schedule Interviews with more professors
- [x] Have Interviews with professors
- [ ] Consolidate information into changes

**Comment by rileyma** [comment]
Interviews about what, specifically?

**Comment by rileyma** [comment]
Interview with Sid on 4/2 @ 4pm

**Comment by rileyma** [comment]
Interview files are on google drive, if you wish to look at them. Work in progress
