### ISSUE TITLE
VM Cors Bug

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#164]
# Description of Issue
Trying to run Compile.io on the VM produces a Cors bug in the Console log of the site.

## How to Reproduce:
 - `ssh` into `compile-io-zach` VM in two separate terminals
 - cd into the `compile.io` directory on the VM.
 - This issue is happening on multiple branches: `develop`, `114-set-assignment-open/close-times`, and `146-linux-env-bug`. Using `sudo git status` to get the current branch may help. If this bug is not present on one branch, it might help to compare the branches to the bug-free branch.
 - In one terminal, use `htop` command to make sure frontend/backend isn't already running. If running, kill the processes running the commands.
 - In one terminal, navigate to the `Frontend/compile-io-frontend-app/` and run `sudo ng serve --prod --host 0.0.0.0`
 - In the other terminal navigate to `Spring_Server/gs-uploading-files-complete/` and run `./gradlew bootRun -D  spring.profiles.active=prod`
 - Open a web browser and enter `http://137.112.104.111:4200/` as your URL. This should be the Compile.io app.
 - Log in with your Rose credentials
 - Make note of the lack of features in the side bar as you log in. Use `Ctrl+SHIFT+i` (or right-click and click `Inspect`, whichever you prefer) to Inspect the window and navigate to the Console output of the browser. 
 - Now you should see the Cors bug.

If this is unclear, contact @rileyma 

## IMPORTANT 
This bug is blocking #146 from progressing, as it prevents testing the end-to-end program on the VM

# Acceptance Criteria
- [x] Replicate the bug on your machine
- [x] Get rid of the bug
- [x] System should function end-to-end with the absence of the bug. Verify that this is so.

**Comment by joshpal97** [comment]
it seems that a simple update of npm fixed the cors bug. 
We should keep an eye on npm from now on
