### ISSUE TITLE
Setup Docker environment for Java

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#21]
Corresponding branch: java-docker-env

**Comment by joshpal97** [comment]
Zach Foote will test

**Comment by joshpal97** [comment]
This was not completely done in sprint 2 and is being moved to sprint 3

**Comment by rileyma** [comment]
`Sending build context to Docker daemon  6.144kB
Step 1/3 : FROM openjdk
latest: Pulling from library/openjdk
no matching manifest for unknown in the manifest list entries`

I'm assuming this is a docker problem? Can't pull the data from Docker Hub which allows me to compile and run java code, which is necessary for this story/issue.
