### ISSUE TITLE
Tutorial on how to run the code locally

### ISSUE THREAD

**Issue by pastorsj** [CompileIO/compile.io#49]
As a user looking at the codebase for the first time, I would like to know how to run the code.

**Acceptance Criteria**
- [ ] A simple markdown file explaining how to start the frontend, backend, and docker

**Comment by donsisco** [comment]
@joshpal97 FYI, the commit will close the issue once it is pulled into master, no need to close it yourself. 
Thanks for using the github keywords for git flow!
 Made better if you add the issue number to the description of the PR, so it links back to the issue, which you can also use github keywords to close via the PR itself.
