### ISSUE TITLE
Store submission information

### ISSUE THREAD

**Issue by pastorsj** [CompileIO/compile.io#54]
As a developer, I want to store the metadata for each submission so that I can reference the submission at a later point.

**Acceptance Criteria**
- [x] Connect Backend Java Spring to a Database such as mongodb
- [x] Store relevant metadata including time of submission, the name of the file, the type of file (java/python...), and the user that submitted the file. At the moment, since we don't have the concept of users or authentication, just prompt the for a username in the UI and store that.

Document database setup information, such as:
- [x] Queries used to create tables
- [x] Schemas
- [x] Entity Relationship Diagram
- [x] (Extra) Any more necessary documents

**Comment by rileyma** [comment]
stretch goal for sprint 2-1

**Comment by donsisco** [comment]
Please dont close issue till code is in our default branch (`develop`) The git hook should close it for you. Closing an issue directly isn't needed.
