### ISSUE TITLE
File Size Restriction

### ISSUE THREAD

**Issue by pastorsj** [CompileIO/compile.io#55]
As a developer, I want to restrict the size of the submission to a reasonable size so that users are unable to upload massive files to the server.

**Acceptance Criteria**
- [x] Restrict the size of the file size on the UI
- [x] Restrict the size of the file size on the API

**Comment by rileyma** [comment]
Acceptance Criteria for Sprint 2-2 has been met. All that remains is the Stretch Goal.

**Comment by rileyma** [comment]
Move stretch goal to new issue
