### ISSUE TITLE
Cleanup docker containers

### ISSUE THREAD

**Issue by pastorsj** [CompileIO/compile.io#56]
As a developer, I need to cleanup docker container after they are being used.

**Acceptance Criteria**
- [x] After a submission has finished running, the docker container should be destroyed.
- [x] After a submission has finished running, the docker image should be destroyed.
- [x] After a submission has finished running, the Dockerfile should be destroyed.
- [x] Create Unit Tests for any added functionality

**Comment by rileyma** [comment]
relevant branch is *docker-cleanup*
