### ISSUE TITLE
Release 2

### ISSUE THREAD

**Issue by pastorsj** [CompileIO/compile.io#57]
As a developer, I need to cut a second release since the functionality completed was significant.

**Acceptance Criteria**
- [ ] Cut a second release with the appropriate title and description so that the stakeholders understand what has changed since the first release.

**Comment by rileyma** [comment]
Functionality change not substantial enough, in my opinion, to warrant a second release. Added cleanup for docker and file size restriction. Will cut Release 2 with addition of container timeouts and python support.

**Comment by donsisco** [comment]
Can we at least add a tag so we can bookmark the state of the project after Sprint 2-2?

**Comment by rileyma** [comment]
Yeah we can add a tag, probably v1.1 rather than v2.0, which is what I believe Release 2 corresponds to.

**Comment by rileyma** [comment]
Tag v1.1 has been updated
