### ISSUE TITLE
Cleanup docker containers Pt2

### ISSUE THREAD

**Issue by pastorsj** [CompileIO/compile.io#58]
As a developer with security and scaling concerns in mind, I need to destroy the docker container after a certain amount of time even if the code is still running.

**Acceptance Criteria**
- [x] After a period of 1 minute, the docker container should be removed and a message should be sent to the UI indicating the code ran for too long

**Comment by rileyma** [comment]
relevant branch is `docker-timeout`

**Comment by donsisco** [comment]
If you put the issue number in the branch name, everyone can quickly see the issue for that branch! 
i.e. `58-docker-timeout` or `docker-timeout-58` or `compileio-58` or `rileyma-58`
Just a tip so you don't have to make a note of which is for which 👍
