### ISSUE TITLE
UI Output Formatting

### ISSUE THREAD

**Issue by pastorsj** [CompileIO/compile.io#59]
As a user, I would like to understand the output so that I can better debug my code that ran on the server.

**Acceptance Criteria**
- [x] Errors should be indicated as errors and should contain a stacktrace
- [x] When the code succeeds, the output is returned and displayed and the user should know that the code succeeded.

**Comment by rileyma** [comment]
I will work with Josh and Foote so that the back-end supplies the front-end with the outputs that need to be displayed, per the needs of the stakeholders.
