### ISSUE TITLE
Docker Cleanup Pt. 3

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#75]
As a professor, I would like to be able to set the time limit a program may run: a variable timeout option on the professor side.

Acceptance Criteria:
- [x] Variable Timeout for Docker Containers
- [x] A set default timer if professor opts not to set
- [x] UI Implementation
#27

**Comment by donsisco** [comment]
What PRs is this issue completed in?

Was this accidentally closed?

**Comment by donsisco** [comment]
I think this was closed in response to https://github.com/CompileIO/compile.io/issues/54, reopening till this code hits `develop`
