### ISSUE TITLE
Professor Class Creation

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#88]
As a Professor, I would like to be able to create classes and add enrolled students to said class.

**Acceptance Criteria**
- [x] Professors can create, delete, or update a class. Delete and Update functions are limited to classes the professor themselves have created
- [x] Professors can add/remove students to/from a class
- [x] Professors can view the Student Roster(s) for their class(es)
- [x] Low Fidelity prototypes

This issue is an `8` because it require Front-end implementation, MongoDB implementation, and then integration testing of the two systems.

This issues replaces #107, which we were unable to complete due to legal reasons outside of our control (see closing comment on the linked issue).

**Comment by joshpal97** [comment]
started on branch 88-professor-branch-creation
